### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by morvagergely** [lmmfranco/nintendo-switch-eshop#154]
Hey there,

Hi,  I have stumbled upon an issue regarding your Switch e-shop module. I'm not sure if it's a bug or the lack of my understanding.
At the end result, some games were missing (like Worms W.M.D), so I have checked your implementation, and seen that you overcame a 100 page limit(?) by querying first by category, then by price range. What was the reasoning behind choosing this path instead of iterating through pages without any filtering applied? Looking at the requests on the Nintendo website, it seems that there is a "page" property in the Algolia API which could just be increased (and I'm concerned that the current method might be flawed in some way that it doesn't fetch all games).

Thank you very much,
Gergely Morva

**Comment by Favna** [comment]
To be entirely frank that bit of code originates from https://github.com/lmmfranco/nintendo-switch-eshop/pull/44 and I haven't really ever actively looked it all over as I don't use this library in my own production projects. The only place where I use the Nintendo API is in a Discord bot (*plugging https://skyra.pw*) where it just takes some filter input and returns up to 10 results returned from the API directly, rather than a middleman library.

That said, I never really noticed any discrepancies in that bit of code. If you think you can improve it then please by all means make your changes, follow the [contribution guidelines](https://github.com/lmmfranco/nintendo-switch-eshop/blob/master/.github/CONTRIBUTING.md) and make a pull request.
