### ISSUE TITLE
Japan search url redirect

### ISSUE THREAD

**Issue by ivanxpru** [lmmfranco/nintendo-switch-eshop#2]
This URL: http://search1.nintendo.co.jp/search/softwareXml.php?hard%5B15%5D=switch_all&hard%5B16%5D=switch&hard%5B17%5D=switch_dl&release_mode=&SearchWindow=1&mode=mf&page=1 not working more. Any ideas?

**Comment by lmmfranco** [comment]
Hi Ivan, it seems Nintendo JP finnally changed their API. 
The new URL is this one, as far as I found:
https://www.nintendo.co.jp/api/search/title?category=products&pf=switch&q=*&count=25

Since a lot of things changed it will have a big impact on the lib.
I'll be working on this as soon as I get some spare time from work.

**Comment by lmmfranco** [comment]
Also found this URL:
https://www.nintendo.co.jp/data/software/xml-system/switch-onsale.xml

This one mostly follows the old format.
However I'm not sure it has all games yet.

**Comment by lmmfranco** [comment]
Fixed in ae3d761
