### ISSUE TITLE
Fetching of Games failed

### ISSUE THREAD

**Issue by croccio** [lmmfranco/nintendo-switch-eshop#261]
Hi i get always this error: 
Fetching of EU Games failed
Fetching of US Games failed
Fetching of JP Games failed

from these requests:
getGamesEurope()
getGamesAmerica()
getGamesJapan()

**Comment by Favna** [comment]
My best guess is that it is somehow related to your network, I just tried it out myself and it still works just fine.

Make sure that you are, for example, not blocking Nintendo's servers because you have a modded Switch and don't want it to go online (a common practise in the Nintendo Switch hacking scene).

Closing this because it's not related to the library.

Sample I tried:
```js
const { getGamesAmerica } = require('nintendo-switch-eshop');

(async () => {
    try {
        const games = await getGamesAmerica();
      
        console.log(games[0]);
    } catch (error) {
        console.error(error)
    }
})();
```
