### ISSUE TITLE
getGamesAmerica only returns half of actual games list

### ISSUE THREAD

**Issue by reinvanimschoot** [lmmfranco/nintendo-switch-eshop#35]
Hey guys,

For some reason, when I use getGamesEurope, I get back 1733 games but when I use getGamesAmerica and use the offset to progress to the list, I get back 949 games. Even when I set the shop option to 'all'.

This is my current implementation:

```
import { getGamesAmerica, getGamesEurope } from 'nintendo-switch-eshop';
import { GameEU, GameUS } from 'nintendo-switch-eshop/dist/interfaces';

const gamesAmerica: GameUS[] = [];
const gamesEurope: GameEU[] = [];

async function getGamesUS(offset = 0) {
  const response = await getGamesAmerica({ shop: 'all' }, offset);
  gamesAmerica.push(...response);

  if (response.length === 200) {
    getGamesUS(gamesAmerica.length);
  } else {
    console.log('WE ARE FINISHED', gamesAmerica.length);
  }
}

async function getGamesEU(offset = 0) {
  const response = await getGamesEurope();
  gamesEurope.push(...response);
  console.log('REPONSE LENGTH', response.length);
}

getGamesUS();
getGamesEU();
```

**Comment by reinvanimschoot** [comment]
Update:

It seems this has to do with the `shop` option. When I use the fetch function in the source code and leave out the shop option, I do get back around the same list of games as the Europe function.

Is there any way this could be fixed? Or should I just fork and continue from there?

**Comment by Favna** [comment]
Couple of things

1. The lib should already do the looping for all the games however it seems that right now it doesn't which is a bug that I'm working on already.

2. For `getGamesAmerica` the default shop option is `ncom` which is in fact far less than the combination of `ncom` and `retail` (aliased by `all`) so that could be related.

3. I see you're importing some interfaces there - I could make sure they are exported properly if you want? In my own production environment I didn't need them so when I rewrote to TS I didn't export them.

**Comment by Favna** [comment]
I'm looking into this. 

Sidenote, I see you're importing some interfaces there - I could make sure they are exported properly if you want? In my own production environment I didn't need them so when I rewrote to TS I didn't export them. I see now why they would be useful however.

**Comment by reinvanimschoot** [comment]
Hi Favna, yeah that would be great! I also noticed that a type is missing for `GameEU` called `image_url_h2x1_s`. You might want to add that as well! Can I ask what you are using this project for?

**Comment by Favna** [comment]
Personally I use it for my discord bot which updates the list on a daily basis and then uses Fuse.js to access it with very rapid fuzzy searches. 

Updating since my last comment - it turns out the lib was not looping itself which it should've done. There should've never been a need for the end-user to loop manually. Franco and I managed to fix this last night but I have the change locally still as I'm still looking into the ommision of the shop parameter and how to handle that nicely.

**Comment by reinvanimschoot** [comment]
Ah perfect! Let me know when it has been updated then.

One other thing I noticed is that when I use `getPrices` with a big list and pagination, I very quickly run into rate problems. However, when I chunk the array of nsuids in groups of 40 and loop over those, I never run into any problems.

```
async function getPriceDataEurope(games: GameEU[]) {
  const gamesChunked = chunkArray(games, 40);
  const gamesWithPriceData = [];

  for (const gamesChunk of gamesChunked) {
    const gamesPriceData = {};
    const nsuids = gamesChunk.map(game => game.nsuid_txt[0]);

    for (const shop of SHOPS_EU) {
      const { prices } = await getPrices(shop, nsuids);

      prices.forEach(price => {
        gamesPriceData[price.title_id] = gamesPriceData[price.title_id] || {};
        gamesPriceData[`${price.title_id}`][shop] = price;
      });
    }

    gamesChunk.forEach(game => {
      gamesWithPriceData.push({
        ...game,
        priceData: gamesPriceData[game.nsuid_txt[0]],
      });
    });
  }

  return gamesWithPriceData;
}
```

**Comment by Favna** [comment]
I should have it all covered now. I also made sure the `getPrices` properly loops, it suffered the same issue as `getGamesAmerica`. As for rate limiting, there isn't much we can do about that.

**Comment by reinvanimschoot** [comment]
Thanks for the quick response and update! I take it is still best to chunk the array of game ids manually to make sure I don't run into any rate limit errors?

**Comment by Favna** [comment]
Yes that is probably the best. 

As for the updates to be released to NPM, I informed Franco that I pushed the changes since he has to make the actual publish.

**Comment by lmmfranco** [comment]
That should be published by now. Thanks you both for your contributions.
